### ISSUE TITLE
Text wrap

### ISSUE THREAD

**Issue by skybldev** [olivier-grech/vscode-irc#8]
First off, I'd like to thank you for the amazing extension you have, despite its limitations! It's a really big help to my workflow! ❤️ 👍 

I usually use your extension in split-screen, and it's kinda weird that it doesn't have text wrapping. It would be great if you added that! :D

**Comment by olivier-grech** [comment]
Hello, I don't have access to VS Code right now, could you clarify what you mean?
Maybe provide a screenshot?

Glad to know it is helping someone!

**Comment by Luxray5474** [comment]
https://i.imgur.com/wdCjpST.gifv

**Comment by olivier-grech** [comment]
Have you tried activating the setting `editor.wordWrap`?
It works for me.
